# Site settings
title: Utkarsh Bajpai
description: Scientist at IBM Research working on semiconductors
baseurl: "" # leave empty for user site
url: "https://utkb23.github.io"

# Author info
author:
  name: "Utkarsh Bajpai"
  bio: "I am Utkarsh Bajpai and I am scientist at IBM Research. I work on semiconductors."
  location: "IBM Research"

# Navigation menu items
nav:
  - title: "About Me"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Personal Blog"
    url: /blog/

# Social links
social:
  - title: "Google Scholar"
    url: "https://scholar.google.com/citations?user=EK4ZIp0AAAAJ&hl=en"
    icon: "scholar"

# Theme
theme: minimal-mistakes-jekyll

# Plugins (for blog and other features)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Blog settings
paginate: 5
paginate_path: "/blog/page:num/"

