title: "Utkarsh Bajpai"
name: "Utkarsh Bajpai"
description: "Scientist at IBM Research working on semiconductors."
url: "https://utkb23.github.io" # Your GitHub Pages URL

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Utkarsh Bajpai"
  bio: "I am Utkarsh Bajpai and I am scientist at IBM Research. I work on semiconductors."

# Navigation
header:
  pages:
    - title: "About Me"
      url: /about/
    - title: "Research"
      url: /research/
    - title: "Publications"
      url: /publications/
    - title: "Personal Blog"
      url: /blog/

# Social
social:
  links:
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=EK4ZIp0AAAAJ&hl=en"
