title: "Home"
name: "Utkarsh Bajpai"
email: "utkbwrk23@gmail.com"
description: "I am Utkarsh Bajpai, a scientist at IBM Research working on semiconductors."

remote_theme: mmistakes/minimal-mistakes

# Social links
author:
  name: "Utkarsh Bajpai"
  avatar: "/assets/images/avatar.png" # optional
  bio: "I am Utkarsh Bajpai and I am scientist at IBM Research. I work on semiconductors."
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=EK4ZIp0AAAAJ&hl=en"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  pages:
    output: true


