title: "Home"
name: "Utkarsh Bajpai"
email: "utkbwrk23@gmail.com"
description: "Hi, I'm Utkarsh, I am a Staff Research Scientist at IBM at the T. J. Watson Research
       Center, at Yorktown Heights, working on some of the coolest problems in advanced
      semiconductor technology. Most of my time goes into figuring out how to make next-gen
      CMOS devices--like super small transitors, going faster and faster each generation.
      I am a physics nerd and just love learning about new things. This website is a collection of 
      some of work and thoughts. Take a look and enjoy!"

remote_theme: mmistakes/minimal-mistakes

# Social links
author:
  name: "Utkarsh Bajpai"
  avatar: "/assets/images/avatar.jpg" # optional
  bio: "Hi, I'm Utkarsh, I am a Staff Research Scientist at IBM Research (T. J. Watson Research
       Center, Yorktown Heights, NY) working on some of the coolest problems in advanced
      semiconductor technology. Most of my time goes into figuring out how to make next-gen
      CMOS devices--like super small transitors, going faster and faster each generation.
      I am a physics nerd and just love learning about new things. This website is a collection of
      some of my work and thoughts. Take a look and enjoy!"
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=EK4ZIp0AAAAJ&hl=en"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  pages:
    output: true


