title: "Utkarsh Bajpai"
name: "Utkarsh Bajpai"
email: "youremail@example.com"
description: "I am Utkarsh Bajpai, a scientist at IBM Research working on semiconductors."

theme: minimal-mistakes-jekyll

# Social links
author:
  name: "Utkarsh Bajpai"
  avatar: "/assets/images/avatar.png" # optional
  bio: "I am Utkarsh Bajpai and I am scientist at IBM Research. I work on semiconductors."
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=EK4ZIp0AAAAJ&hl=en"

# Navigation
header_pages:
  - about.md
  - research.md
  - publications.md
  - blog.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
